name: Deploy Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build docs
        run: |
          sphinx-build -b html source build/html

      - name: Add CNAME
        run: echo "docs.trivox.io" > build/html/CNAME

      - name: Copy built evolving-ideas docs into build
        run: |
          cp -r evolving-ideas build/html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          publish_branch: gh-pages
          cname: docs.trivox.io
          enable_jekyll: false
